name: Build and release
on: 
  push:
    branches:
      - 'main'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Create build
        run: npm run build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins:
            - conventional-changelog-eslint
            - '@semantic-release/git'
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}