name: Build and release
on: 
  push:
    branches:
      - 'main'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Create build
        run: npm run build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            conventional-changelog-eslint
            '@semantic-release/git'
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
  build-storybook:
    name: Build storybook static website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 16.x
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build static files
        run: npm run build-storybook
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: storybook-build
          path: storybook-static
          retention-days: 1
    
  push-to-pages-repo: 
    name: Push storybook build to pages repo
    runs-on: ubuntu-latest
    needs: build-storybook
    steps: 
      - name: Checkout Pages repo code
        uses: actions/checkout@v3
        with: 
          repository: SinxRofozoteron/SinxRofozoteron.github.io
          token: ${{ secrets.STATIC_WEBSITE_TOKEN }}
      - name: Remove previous build
        run: |
          shopt -s extglob
          rm -r !("README.md")
      - name: Get storybook build
        uses: actions/download-artifact@v3
        with:
          name: storybook-build
      - name: Commit new build and push to remote repo
        run: |
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          git add .
          git commit -m "Updated storybook build"
          git push
        